### ISSUE TITLE
Move to pipx

### ISSUE THREAD

**Issue by julien-blanchon** [vict0rsch/gitmopy#11]
Hey :wave:,
This is cool, thanks for making it open source !
I think this package don't need to belong to user Python system, this kind of things will be better in a isolated environments using `pipx`.
`pip install gitmopy` is a kind of a bad practice for such things, I would change it to `pipx install gitmopy` or maybe provide both in the documentation.

**Comment by vict0rsch** [comment]
Right, thanks! Done.
